export const PHOTO_UPLOAD_PRIMARY_QUALITY = 82;
export const PHOTO_UPLOAD_FALLBACK_QUALITY = 70;
export const PHOTO_UPLOAD_MAX_DIMENSION_PX = 2000;
export const PHOTO_UPLOAD_MODERATION_DIMENSION_PX = 512;
export const PHOTO_UPLOAD_MODERATION_QUALITY = 75;
